In [10]:
import numpy as np
import pandas as pd


In [11]:
data_pd = pd.read_csv('data.csv', header=None)
data_pd

0     1     2    3     4     5     6     7     8     9   ...   47  \
0     0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.0   
1     0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94  ...  0.0   
2     0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25  ...  0.0   
3     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63  ...  0.0   
4     0.00  0.00  0.00  0.0  1.85  0.00  0.00  1.85  0.00  0.00  ...  0.0   
...    ...   ...   ...  ...   ...   ...   ...   ...   ...   ...  ...  ...   
3675  0.00  0.00  1.19  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
3676  0.31  0.00  0.62  0.0  0.00  0.31  0.00  0.00  0.00  0.00  ...  0.0   
3677  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   
3678  0.96  0.00  0.00  0.0  0.32  0.00  0.00  0.00  0.00  0.00  ...  0.0   
3679  0.00  0.00  0.65  0.0  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.0   

        48     49   50     51     52     53     54     55      56  
0     0.00  0.000  0.0  0.778  0.000  0.000  3.756   61.0   278.0  
1     0.00  0.132  0.0  0.372  0.180  0.048  5.114  101.0  1028.0  
2     0.01  0.143  0.0  0.276  0.184  0.010  9.821  485.0  2259.0  
3     0.00  0.137  0.0  0.137  0.000  0.000  3.537   40.0   191.0  
4     0.00  0.223  0.0  0.000  0.000  0.000  3.000   15.0    54.0  
...    ...    ...  ...    ...    ...    ...    ...    ...     ...  
3675  0.00  0.000  0.0  0.000  0.000  0.000  1.000    1.0    24.0  
3676  0.00  0.232  0.0  0.000  0.000  0.000  1.142    3.0    88.0  
3677  0.00  0.000  0.0  0.353  0.000  0.000  1.555    4.0    14.0  
3678  0.00  0.057  0.0  0.000  0.000  0.000  1.147    5.0    78.0  
3679  0.00  0.000  0.0  0.125  0.000  0.000  1.250    5.0    40.0  

[3680 rows x 57 columns]

In [12]:
data = np.genfromtxt('data.csv', delimiter=',', skip_header=1)
data.shape
data

array([[2.100e-01, 2.800e-01, 5.000e-01, ..., 5.114e+00, 1.010e+02,
        1.028e+03],
       [6.000e-02, 0.000e+00, 7.100e-01, ..., 9.821e+00, 4.850e+02,
        2.259e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 3.537e+00, 4.000e+01,
        1.910e+02],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.555e+00, 4.000e+00,
        1.400e+01],
       [9.600e-01, 0.000e+00, 0.000e+00, ..., 1.147e+00, 5.000e+00,
        7.800e+01],
       [0.000e+00, 0.000e+00, 6.500e-01, ..., 1.250e+00, 5.000e+00,
        4.000e+01]])

In [8]:
base_num_4_example = 5
range_4_example = 5
fold_4_example = np.genfromtxt('experiments/base%d_fold%d.csv' % (base_num_4_example, range_4_example), delimiter=',', dtype=np.int64)
fold_4_example.shape
fold_4_example


array([[1460,    0],
       [ 973,    1],
       [ 462,    0],
       [2572,    0],
       [3308,    0],
       [3647,    0],
       [1804,    0],
       [1541,    0],
       [ 144,    0],
       [2770,    0],
       [1151,    0],
       [2806,    0],
       [2866,    0],
       [1239,    1],
       [1422,    0],
       [2095,    0],
       [ 722,    1],
       [3674,    0],
       [2390,    0],
       [1057,    0],
       [1210,    0],
       [3194,    0],
       [2205,    0],
       [1675,    0],
       [2736,    0],
       [1805,    0],
       [2042,    1],
       [3027,    0],
       [1628,    0],
       [ 959,    0],
       [ 777,    0],
       [3507,    0],
       [ 499,    0],
       [2778,    0],
       [2444,    0],
       [1023,    0],
       [2321,    0],
       [3000,    0],
       [2789,    1],
       [2190,    0],
       [ 905,    0],
       [ 111,    0],
       [ 889,    0],
       [2720,    0],
       [2412,    0],
       [3518,    0],
       [1987,    0],
       [1196,

In [9]:
target = np.genfromtxt('targets.csv')
target.shape
target 

array([1., 1., 1., ..., 0., 0., 0.])

: 